version: '3'
services:
  sso:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./services/sso:/usr/src/services/sso
      - ./services/schemas:/usr/src/services/sso/schemas
      - ./.venv:/usr/src/.venv
    working_dir: /usr/src/
    command: bash -c "cd services/sso && pipenv run python init_db.py && pipenv run python -m uvicorn main:app --host 0.0.0.0 --reload"
    ports:
      - 8000:8000
  
  tasks:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./services/tasks:/usr/src/services/tasks
      - ./services/schemas:/usr/src/services/tasks/schemas
      - ./.venv:/usr/src/.venv
    working_dir: /usr/src/
    command: bash -c "cd services/tasks && pipenv run python init_db.py && pipenv run python -m uvicorn main:app --host 0.0.0.0 --reload"
    ports:
      - 8001:8000

  tasks_consumer:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./services/tasks:/usr/src/services/tasks
      - ./services/schemas:/usr/src/services/tasks/schemas
      - ./.venv:/usr/src/.venv
    working_dir: /usr/src/
    command: bash -c "cd services/tasks && pipenv run python consumer.py"

  accounting:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./services/accounting:/usr/src/services/accounting
      - ./services/schemas:/usr/src/services/accounting/schemas
      - ./.venv:/usr/src/.venv
    working_dir: /usr/src/
    command: bash -c "cd services/accounting && pipenv run python init_db.py && pipenv run python -m uvicorn main:app --host 0.0.0.0 --reload"
    ports:
      - 8002:8000

  accounting_consumer:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./services/accounting:/usr/src/services/accounting
      - ./services/schemas:/usr/src/services/accounting/schemas
      - ./.venv:/usr/src/.venv
    working_dir: /usr/src/
    command: bash -c "cd services/accounting && pipenv run python consumer.py"


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    logging:
      driver: none

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    logging:
      driver: none

  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29093:29092
    hostname: kafka2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    logging:
      driver: none

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092,kafka2:29093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - kafka2
      - zookeeper
    logging:
      driver: none

