
### sso url

curl http://sso:8000/

### sso docs

curl http://sso:8000/docs


### sso get token

curl -X 'POST' \
  'http://sso:8000/token' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'grant_type=&username=johndoe&password=secret&scope=&client_id=&client_secret='

### sso check

curl -X 'GET' \
  'http://sso:8000/users/me' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwicm9sZSI6InBhcnJvdCIsImV4cCI6MTY5MTY3Mjg1MX0.akNbolNgV4F9zcvWSttiCTxVemS_8dZb9nXT0y16B14'

### tasks get token

curl -X 'POST' \
  'http://tasks:8000/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'grant_type=&username=johndoe&password=secret&scope=&client_id=&client_secret='

### tasks list

curl -X 'GET' \
  'http://tasks:8000/tasks' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwicm9sZSI6InBhcnJvdCIsImV4cCI6MTY5MTY3Mjg3MX0.4xUItrWjdvoKeJSWWLLMLwNqC_UgnqW_b9t_BzWv8o8'

### manager get token

curl -X 'POST' \
  'http://tasks:8000/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'grant_type=&username=manager&password=secret&scope=&client_id=&client_secret='


### manager get tasks

curl -X 'GET' \
  'http://tasks:8000/tasks' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYW5hZ2VyIiwicm9sZSI6Im1hbmFnZXIiLCJleHAiOjE2OTE2NzM2ODV9.mzYTXW6LKeN28BsLB5C3I5vzLXCqYkw0BJqyC26ko1M'


### kafka UI

curl http://localhost:8090/


### register new user

curl -X 'POST' \
  'http://sso:8000/register' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"username":"1wws1qjod2snde2z","password":"secret","role":"parrot"}'
